name: Setup
description: Checks out project, installs Node.js and dependencies

inputs:
  node-version:
    description: Node.js version to use
    required: true
    default: latest

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile --no-progress
      shell: bash
