name: Setup
description: Sets up Node.js and installs dependencies with Yarn

inputs:
  node-version:
    description: Node.js version to use
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile --no-progress
      shell: bash
