default:
  interruptible: false
  image: node:18-alpine
  cache:
    policy: pull-push
    when: on_success
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .yarn
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile --no-progress

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - yarn run build

test-job:
  stage: test
  script:
    - yarn run test

lint-job:
  stage: test
  script:
    - yarn run lint

deploy-job:
  stage: deploy
  environment: production
  only:
    - main
  before_script: # Setup SSH
    - 'command -v ssh-agent >/dev/null || (apk update && apk add --no-progress openssh)'

    ## Give the right permissions, otherwise ssh-add will refuse to add files.
    - chmod 400 "$SSH_PRIVATE_KEY"
    - eval $(ssh-agent -s)
    - ssh-add "$SSH_PRIVATE_KEY"

    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying application..."
    - ssh $SSH_USER@$SSH_HOST "/app/deploy.sh"
    - echo "Application successfully deployed."
