version: '3'

networks:
  fs3-pokedex:

volumes:
  mongo-data:

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - fs3-pokedex
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      target: development
    env_file: .env
    restart: unless-stopped
    networks:
      - fs3-pokedex
    ports:
      - 3001:3001
    volumes:
      - ./:/app
