name: Deploy

on:
  pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Run test workflow
        uses: ./.github/actions/test
      # - name: Copy deploy script
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: deploy.sh
      #     target: /app
      # - name: Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: /app/deploy.sh github
