name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test.yml

      - uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /app/deploy.sh github
