name: Test

on:
  pull_request:

jobs:
  test:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        uses: ./.github/actions/test
