name: Test

on:
  pull_request:

jobs:
  test:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        # with:
        #   node-version: 18

      - name: version
        run: node --version

      - name: Run tests
        uses: ./.github/actions/test
